<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ8K6ySV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ8K6ySV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ8K6ySV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ8K6ySV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ8K6ySV\App_KernelDevDebugContainer([
    'container.build_hash' => 'J8K6ySV',
    'container.build_id' => 'a95ed8dd',
    'container.build_time' => 1710321609,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ8K6ySV');
