controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
uservue:
  path: /uservue
  controller: App\Controller\UservueController::index

#ADMINS
adminproducts:
  path: /adminproducts
  controller: App\Controller\AdminproductsController::index
#CRUD
#Ajouter produits
adminajouterproducts:
  path: /product/new
  controller: App\Controller\AdminproductsController::new
#Supp
admindeleteproducts:
  path: /product/delete
  controller: App\Controller\AdminproductsController::delete
#UPDATE
adminupdateproducts:
  path: /product/update
  controller: App\Controller\AdminupdateController::update
app_edit_product:
  path: "/editproduct/{id}"
  controller: 'App\Controller\AdminproductsController::editProduct'
  methods: ["POST"]
#COMPTE ADMIN
compteadmin:
  path: /compteadmin
  controller: App\Controller\AdminproductsController::adminPage
#PANIER USER
api_user_panier:
  path: /api/user/panier
  controller: App\Controller\UserController::getUserPanier
panier_index:
  path: /user/panier
  controller: App\Controller\UserController::getUserPanier
#ADD QUANTITY PRODUCTS
add_quantity:
  path: "/admin/products/{productId}/add_quantity"
  methods: ["POST"]
  controller: 'App\Controller\AdminproductsController::addQuantity'
remove_quantity:
  path: "/admin/products/{productId}/remove_quantity"
  methods: ["POST"]
  controller: 'App\Controller\AdminproductsController::removeQuantity'
admin_products_list:
  path: "/admin/products/list"
  controller: 'App\Controller\AdminproductsController::index'

# Routes pour afficher les détails du produit ou de la promotion dans ACCUEIL
details_produit:
  path: "/details-produit/{id}"
  controller: 'App\Controller\AccueilController::detailsProduit'
details_promotion:
  path: "/details-promotion/{id}"
  controller: 'App\Controller\AccueilController::detailsPromotion'

app_contact:
  path: "/contact"
  controller: 'App\Controller\AccueilController::indexcontact'

api_loyalty_card:
  path: /api/loyalty-card
  controller: App\Controller\UservueController::getLoyaltyCard
  methods: [GET]

user_profile_view:
  path: /user/profile
  controller: App\Controller\UserController::viewProfile

app_search_products:
  path: /search-products
  controller: App\Controller\UservueController::searchProducts
  methods: [GET, POST]

user_category_products:
  path: /user/uservue/categorie/{category}
  controller: App\Controller\UservueController::showCategoryProducts
