controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
uservue:
  path: /uservue
  controller: App\Controller\UservueController::index

#ADMINS
adminproducts:
  path: /adminproducts
  controller: App\Controller\AdminproductsController::index

#CRUD
adminajouterproducts:
  path: /product/new
  controller: App\Controller\AdminproductsController::new
admindeleteproducts:
  path: /product/delete
  controller: App\Controller\AdminproductsController::delete
