<?php

namespace ContainerXZUuPxI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TnbX4f3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TnbX4f3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TnbX4f3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'product' => ['privates', '.errored..service_locator.TnbX4f3.App\\Entity\\Products', NULL, 'Cannot autowire service ".service_locator.TnbX4f3": it needs an instance of "App\\Entity\\Products" but this type has been excluded in "config/services.yaml".'],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'product' => 'App\\Entity\\Products',
            'urlGenerator' => '?',
        ]);
    }
}
