<?php

namespace ContainerXZUuPxI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FFPQXfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F_fPQXf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F_fPQXf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AccueilController::index' => ['privates', '.service_locator.C8cIOOc', 'get_ServiceLocator_C8cIOOcService', true],
            'App\\Controller\\AdminproductsController::deleteProduct' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\AdminproductsController::deleteProducts' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\AdminproductsController::editProduct' => ['privates', '.service_locator.hAIPoGV', 'get_ServiceLocator_HAIPoGVService', true],
            'App\\Controller\\AdminproductsController::editProductForm' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\AdminproductsController::index' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\AdminproductsController::updateProducts' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\PromoAdminController::delete' => ['privates', '.service_locator.DtsKEqY', 'get_ServiceLocator_DtsKEqYService', true],
            'App\\Controller\\PromoAdminController::edit' => ['privates', '.service_locator.DtsKEqY', 'get_ServiceLocator_DtsKEqYService', true],
            'App\\Controller\\PromoAdminController::index' => ['privates', '.service_locator.1j13wVw', 'get_ServiceLocator_1j13wVwService', true],
            'App\\Controller\\PromoAdminController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PromoAdminController::show' => ['privates', '.service_locator.mcb6ZOo', 'get_ServiceLocator_Mcb6ZOoService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UservueController::addToCart' => ['privates', '.service_locator.TnbX4f3', 'get_ServiceLocator_TnbX4f3Service', true],
            'App\\Controller\\UservueController::getUserPanier' => ['privates', '.service_locator.XjqUGgN', 'get_ServiceLocator_XjqUGgNService', true],
            'App\\Controller\\UservueController::index' => ['privates', '.service_locator.rP290eI', 'get_ServiceLocator_RP290eIService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AccueilController:index' => ['privates', '.service_locator.C8cIOOc', 'get_ServiceLocator_C8cIOOcService', true],
            'App\\Controller\\AdminproductsController:deleteProduct' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\AdminproductsController:deleteProducts' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\AdminproductsController:editProduct' => ['privates', '.service_locator.hAIPoGV', 'get_ServiceLocator_HAIPoGVService', true],
            'App\\Controller\\AdminproductsController:editProductForm' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\AdminproductsController:index' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\AdminproductsController:updateProducts' => ['privates', '.service_locator.czOFGB2', 'get_ServiceLocator_CzOFGB2Service', true],
            'App\\Controller\\PromoAdminController:delete' => ['privates', '.service_locator.DtsKEqY', 'get_ServiceLocator_DtsKEqYService', true],
            'App\\Controller\\PromoAdminController:edit' => ['privates', '.service_locator.DtsKEqY', 'get_ServiceLocator_DtsKEqYService', true],
            'App\\Controller\\PromoAdminController:index' => ['privates', '.service_locator.1j13wVw', 'get_ServiceLocator_1j13wVwService', true],
            'App\\Controller\\PromoAdminController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PromoAdminController:show' => ['privates', '.service_locator.mcb6ZOo', 'get_ServiceLocator_Mcb6ZOoService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UservueController:addToCart' => ['privates', '.service_locator.TnbX4f3', 'get_ServiceLocator_TnbX4f3Service', true],
            'App\\Controller\\UservueController:getUserPanier' => ['privates', '.service_locator.XjqUGgN', 'get_ServiceLocator_XjqUGgNService', true],
            'App\\Controller\\UservueController:index' => ['privates', '.service_locator.rP290eI', 'get_ServiceLocator_RP290eIService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AccueilController::index' => '?',
            'App\\Controller\\AdminproductsController::deleteProduct' => '?',
            'App\\Controller\\AdminproductsController::deleteProducts' => '?',
            'App\\Controller\\AdminproductsController::editProduct' => '?',
            'App\\Controller\\AdminproductsController::editProductForm' => '?',
            'App\\Controller\\AdminproductsController::index' => '?',
            'App\\Controller\\AdminproductsController::updateProducts' => '?',
            'App\\Controller\\PromoAdminController::delete' => '?',
            'App\\Controller\\PromoAdminController::edit' => '?',
            'App\\Controller\\PromoAdminController::index' => '?',
            'App\\Controller\\PromoAdminController::new' => '?',
            'App\\Controller\\PromoAdminController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UservueController::addToCart' => '?',
            'App\\Controller\\UservueController::getUserPanier' => '?',
            'App\\Controller\\UservueController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AccueilController:index' => '?',
            'App\\Controller\\AdminproductsController:deleteProduct' => '?',
            'App\\Controller\\AdminproductsController:deleteProducts' => '?',
            'App\\Controller\\AdminproductsController:editProduct' => '?',
            'App\\Controller\\AdminproductsController:editProductForm' => '?',
            'App\\Controller\\AdminproductsController:index' => '?',
            'App\\Controller\\AdminproductsController:updateProducts' => '?',
            'App\\Controller\\PromoAdminController:delete' => '?',
            'App\\Controller\\PromoAdminController:edit' => '?',
            'App\\Controller\\PromoAdminController:index' => '?',
            'App\\Controller\\PromoAdminController:new' => '?',
            'App\\Controller\\PromoAdminController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UservueController:addToCart' => '?',
            'App\\Controller\\UservueController:getUserPanier' => '?',
            'App\\Controller\\UservueController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
