<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT5MCAHX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT5MCAHX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT5MCAHX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT5MCAHX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT5MCAHX\App_KernelDevDebugContainer([
    'container.build_hash' => 'T5MCAHX',
    'container.build_id' => '0e28266f',
    'container.build_time' => 1711322333,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT5MCAHX');
