<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5D474xA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5D474xA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5D474xA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5D474xA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5D474xA\App_KernelDevDebugContainer([
    'container.build_hash' => '5D474xA',
    'container.build_id' => '109dbfdc',
    'container.build_time' => 1711553387,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5D474xA');
