<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSiIQykW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSiIQykW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSiIQykW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSiIQykW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSiIQykW\App_KernelDevDebugContainer([
    'container.build_hash' => 'SiIQykW',
    'container.build_id' => '5bea0f1f',
    'container.build_time' => 1711037728,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSiIQykW');
